export const GameId = {
  DICE: 'dice',
  MINES: 'mines',
  HILO: 'hilo',
  KENO: 'keno',
  WHEEL: 'wheel',
  MINI_ROULETTE: 'mini-roulette',
  PLINKO: 'plinko',
  HOTLINE: 'hotline',
  TOWER: 'tower',
  ROCKET: 'rocket',
  AVIATOR: 'aviator',
  SPACE_FLEET: 'space-fleet',
  JETX: 'jetx',
  BALLOON: 'balloon',
  JETX3: 'jetx3',
  DOUBLE_X: 'double-x',
  PLINKO_X: 'plinko-x',
  CARNIVAL: 'carnival',
} as const;

export type GameIdType = (typeof GameId)[keyof typeof GameId];

export type GameCategory = 'single-step' | 'multi-step' | 'realtime-crash';

export interface GameMetadata {
  id: GameIdType;
  name: string;
  nameZh: string;
  category: GameCategory;
  description: string;
  descriptionZh: string;
  rtp: number;
  icon: string;
  enabled: boolean;
  thumbnail?: string;
}

export const GAMES_REGISTRY: Record<GameIdType, GameMetadata> = {
  [GameId.DICE]: {
    id: GameId.DICE,
    name: 'Dice',
    nameZh: '骰子',
    category: 'single-step',
    description: 'Classic crypto dice. Choose over/under and roll.',
    descriptionZh: '经典加密骰子，选高低后掷骰',
    rtp: 0.99,
    icon: 'dice',
    enabled: true,
  },
  [GameId.MINES]: {
    id: GameId.MINES,
    name: 'Mines',
    nameZh: '踩地雷',
    category: 'multi-step',
    description: 'Reveal gems while avoiding mines. Cash out anytime.',
    descriptionZh: '翻开鑽石，避开地雷，随时可领奖',
    rtp: 0.97,
    icon: 'mines',
    enabled: true,
  },
  [GameId.HILO]: {
    id: GameId.HILO,
    name: 'Hi-Lo',
    nameZh: '猜大小',
    category: 'multi-step',
    description: 'Guess if the next card is higher or lower.',
    descriptionZh: '猜下一张牌是高还是低',
    rtp: 0.99,
    icon: 'cards',
    enabled: true,
  },
  [GameId.KENO]: {
    id: GameId.KENO,
    name: 'Keno',
    nameZh: '基諾',
    category: 'single-step',
    description: 'Pick numbers and match the draw.',
    descriptionZh: '选号对奖',
    rtp: 0.97,
    icon: 'keno',
    enabled: true,
  },
  [GameId.WHEEL]: {
    id: GameId.WHEEL,
    name: 'Color Wheel',
    nameZh: '彩色转轮',
    category: 'single-step',
    description: 'Spin the wheel and win.',
    descriptionZh: '旋转轮盘，对上颜色即赢',
    rtp: 0.96,
    icon: 'wheel',
    enabled: true,
  },
  [GameId.MINI_ROULETTE]: {
    id: GameId.MINI_ROULETTE,
    name: 'Mini Roulette',
    nameZh: '迷你轮盘',
    category: 'single-step',
    description: 'European roulette with 13 slots.',
    descriptionZh: '欧式迷你轮盘',
    rtp: 0.9615,
    icon: 'roulette',
    enabled: true,
  },
  [GameId.PLINKO]: {
    id: GameId.PLINKO,
    name: 'Plinko',
    nameZh: '弹珠台',
    category: 'single-step',
    description: 'Drop balls through pegs into multiplier slots.',
    descriptionZh: '弹珠穿过釘阵落入倍率槽',
    rtp: 0.99,
    icon: 'plinko',
    enabled: true,
  },
  [GameId.HOTLINE]: {
    id: GameId.HOTLINE,
    name: 'Hotline',
    nameZh: '热线',
    category: 'single-step',
    description: 'Neon-themed slot machine.',
    descriptionZh: '霓虹风格老虎机',
    rtp: 0.97,
    icon: 'slots',
    enabled: true,
  },
  [GameId.TOWER]: {
    id: GameId.TOWER,
    name: 'Tower X',
    nameZh: '疊塔',
    category: 'multi-step',
    description: 'Climb the tower, avoid traps.',
    descriptionZh: '爬塔避陷阱',
    rtp: 0.97,
    icon: 'tower',
    enabled: true,
  },
  [GameId.ROCKET]: {
    id: GameId.ROCKET,
    name: 'Rocket',
    nameZh: '火箭',
    category: 'realtime-crash',
    description: 'Cash out before the rocket crashes.',
    descriptionZh: '火箭爆炸前领奖',
    rtp: 0.97,
    icon: 'rocket',
    enabled: true,
  },
  [GameId.AVIATOR]: {
    id: GameId.AVIATOR,
    name: 'Aviator',
    nameZh: '飞行员',
    category: 'realtime-crash',
    description: 'The original crash game.',
    descriptionZh: 'Crash 游戏开创者',
    rtp: 0.97,
    icon: 'aviator',
    enabled: true,
  },
  [GameId.SPACE_FLEET]: {
    id: GameId.SPACE_FLEET,
    name: 'Space Fleet',
    nameZh: '太空舰队',
    category: 'realtime-crash',
    description: 'Sci-fi themed crash.',
    descriptionZh: '科幻主题 Crash',
    rtp: 0.97,
    icon: 'spaceship',
    enabled: true,
  },
  [GameId.JETX]: {
    id: GameId.JETX,
    name: 'JetX',
    nameZh: '飆速X',
    category: 'realtime-crash',
    description: 'Jet plane crash game.',
    descriptionZh: '噴射机 Crash',
    rtp: 0.97,
    icon: 'jet',
    enabled: true,
  },
  [GameId.BALLOON]: {
    id: GameId.BALLOON,
    name: 'Balloon',
    nameZh: '气球',
    category: 'realtime-crash',
    description: 'Inflate the balloon before it pops.',
    descriptionZh: '气球爆炸前领奖',
    rtp: 0.97,
    icon: 'balloon',
    enabled: true,
  },
  [GameId.JETX3]: {
    id: GameId.JETX3,
    name: 'JetX3',
    nameZh: '飆速X3',
    category: 'realtime-crash',
    description: 'Three jets, three bets per round.',
    descriptionZh: '三架噴射机同局下注',
    rtp: 0.97,
    icon: 'jet3',
    enabled: true,
  },
  [GameId.DOUBLE_X]: {
    id: GameId.DOUBLE_X,
    name: 'Double X',
    nameZh: '双倍X',
    category: 'realtime-crash',
    description: 'Two multipliers racing.',
    descriptionZh: '双倍率 Crash',
    rtp: 0.97,
    icon: 'double',
    enabled: true,
  },
  [GameId.PLINKO_X]: {
    id: GameId.PLINKO_X,
    name: 'Plinko X',
    nameZh: '掉珠挑战X',
    category: 'realtime-crash',
    description: 'Plinko meets Crash.',
    descriptionZh: 'Plinko 加 Crash 混合',
    rtp: 0.97,
    icon: 'plinko-x',
    enabled: true,
  },
  [GameId.CARNIVAL]: {
    id: GameId.CARNIVAL,
    name: 'Carnival',
    nameZh: '狂欢节',
    category: 'single-step',
    description: 'Carnival-themed roulette.',
    descriptionZh: '嘉年華风轮盘',
    rtp: 0.97,
    icon: 'carnival',
    enabled: true,
  },
};

export const ENABLED_GAMES = Object.values(GAMES_REGISTRY).filter((g) => g.enabled);

export function getGameMeta(id: string): GameMetadata | undefined {
  return GAMES_REGISTRY[id as GameIdType];
}
