const LOBBY_COVER_OVERRIDES: Record<string, string> = {
  hotline: '/slots/cyber/cover-v2.png',
  'fruit-slot': '/slots/fruit/cover-v2.png',
  'fortune-slot': '/slots/fortune/cover-v2.png',
  'ocean-slot': '/slots/ocean/cover-v2.png',
  'temple-slot': '/slots/temple/cover-v2.png',
  'candy-slot': '/slots/candy/cover-v2.png',
  'sakura-slot': '/slots/sakura/cover-v2.png',
  'thunder-slot': '/slots/thunder/cover-v2.png',
  'dragon-mega-slot': '/slots/dragon-mega/cover-v2.png',
  'nebula-slot': '/slots/nebula/cover-v2.png',
  'jungle-slot': '/slots/jungle/cover-v2.png',
  'vampire-slot': '/slots/vampire/cover-v2.png',
  baccarat: '/game-art/baccarat/cover.png',
  'baccarat-nova': '/games/baccarat.jpg',
  'baccarat-imperial': '/game-art/baccarat/background.png',
  blackjack: '/game-art/blackjack/cover-v2.png',
  'twenty-one-half-doll': '/game-art/local-table/ten-half-doll-cover.webp',
  'twenty-one-half-bunny': '/game-art/local-table/ten-half-bunny-cover.webp',
  'twenty-one-half-star': '/game-art/local-table/ten-half-star-cover.webp',
  'tui-tongzi-dragon': '/game-art/local-table/tui-tongzi-dragon-cover.webp',
  'tui-tongzi-lion': '/game-art/local-table/tui-tongzi-lion-cover.webp',
  'tui-tongzi-jade': '/game-art/local-table/tui-suozi-jade-cover.webp',
  'tui-tongzi-neon': '/game-art/local-table/tui-suozi-neon-cover.webp',
  'tui-tongzi-gold': '/game-art/local-table/tui-wanzi-gold-cover.webp',
  'black-dot-tianjiu': '/game-art/local-table/black-dot-tianjiu-cover.webp',
  'black-dot-royal': '/game-art/local-table/black-dot-royal-cover.webp',
  'black-dot-street': '/game-art/local-table/black-dot-street-cover.webp',
  'black-dot-shadow': '/game-art/local-table/black-dot-shadow-cover.webp',
  'black-dot-gold': '/game-art/local-table/black-dot-gold-cover.webp',
  'card-war': '/game-art/local-table/card-war-cover.webp',
  'card-war-neon': '/game-art/local-table/card-war-neon-cover.webp',
  'card-war-gold': '/game-art/local-table/card-war-gold-cover.webp',
  'card-war-crystal': '/game-art/local-table/card-war-crystal-cover.webp',
  dice: '/game-art/dice/cover-v2.png',
  mines: '/game-art/mines/cover-v2.png',
  hilo: '/game-art/hilo/cover-v2.png',
  plinko: '/game-art/plinko/cover-v2.png',
  keno: '/game-art/keno/cover-v2.png',
  wheel: '/game-art/wheel/cover-v2.png',
  'mini-roulette': '/game-art/mini-roulette/cover-v2.png',
  tower: '/game-art/tower/cover-v2.png',
  'chicken-road': '/game-art/chicken-road/cover.png',
  carnival: '/game-art/carnival/cover-v2.png',
  rocket: '/games/lobby/rocket-v2.png',
  aviator: '/games/lobby/aviator-v2.png',
  'space-fleet': '/games/lobby/space-fleet-v2.png',
  jetx: '/games/lobby/jetx-v2.png',
  balloon: '/games/lobby/balloon-v2.png',
  jetx3: '/games/lobby/jetx3-v2.png',
  'double-x': '/games/lobby/double-x-v2.png',
  'plinko-x': '/games/lobby/plinko-x-v2.png',
};

export function getLobbyGameCover(gameId: string): string {
  return LOBBY_COVER_OVERRIDES[gameId] ?? `/games/${gameId}.jpg`;
}
